In [68]:
import pandas as pd

In [69]:
orig_df = pd.read_excel('../Data/Tehran_Indexes_Price_NoRegime.xlsx').set_index('date')

In [81]:
kani_df = pd.read_excel('../Data/kani.xlsx').set_index(pd.to_datetime(kani_df['date']))

/var/folders/mj/xw3m0dws3yq8j2md9n8j3g940000gn/T/ipykernel_3638/2780328453.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  kani_df = pd.read_excel('../Data/kani.xlsx').set_index(pd.to_datetime(kani_df['date']))

In [83]:
kani_df.drop('date', axis=1, inplace=True)

In [87]:
kani_df = kani_df[::-1]

In [93]:
final_df = pd.merge(orig_df, kani_df, how='outer', on='date').dropna()

In [95]:
final_df.to_excel('TH.xlsx')

In [105]:
import numpy as np

In [106]:
def price_return(p):
    pr = []
    for i in range(1, len(p)):
        pr.append(np.log(p[i])-np.log(p[i-1]))
    return pr

In [107]:
complete_network_df_returned = final_df.copy()
for i in range(len(complete_network_df_returned.columns)):
    returned_col = price_return(complete_network_df_returned[complete_network_df_returned.columns[i]].values)
    returned_col.append(0)
    returned_col = np.array(returned_col)
    returned_col = returned_col - np.mean(returned_col)
    returned_col = returned_col/np.std(returned_col)
    complete_network_df_returned[complete_network_df_returned.columns[i]] = returned_col

In [118]:
complete_network_df_returned.iloc[:-1].to_excel('TTH.xlsx')

In [117]:
complete_network_df_returned

,index,Brent Oil,Coin,Euro,USD,CPI,HOUSE,M1,M2,GDP,...,SarmayeGozari,Bank,SayerMali,HamlVaNaghl,Bimeh,Amlakva,Rayaneh,FaniVaMohandesi,Mali,Value
date,,,,,,,,,,,,,,,,,,,,,
2011-04-03,1.589072,1.204538,-0.064675,0.003352,0.074195,0.254184,-0.085913,0.576417,0.006245,0.286194,...,2.194589,0.133014,0.547866,-0.048002,0.505688,-0.499292,1.954840,1.634032,0.064607,2.018185
2011-04-04,1.722792,0.470067,-0.064675,0.036768,0.167699,0.243951,-0.089951,0.541727,-0.009378,0.281783,...,1.815667,0.198958,-0.136209,0.043659,-0.455753,0.011184,2.114437,1.645781,0.055551,2.142481
2011-04-05,1.019672,0.042583,0.468823,0.601798,0.166652,0.233752,-0.093977,0.507283,-0.024954,0.277406,...,0.457524,0.506716,-0.662157,0.141696,-0.570506,0.633553,-0.466937,1.052189,0.063312,1.447213
2011-04-06,1.014590,0.230965,0.462817,0.593530,-0.067326,2.006083,0.406780,1.861363,1.285347,1.036355,...,0.030868,0.260946,-1.065222,1.847740,-0.425568,0.496462,-1.418319,0.646751,0.023379,1.856502
2011-04-09,-0.905655,0.229965,0.167873,0.099266,-0.020655,0.193289,-0.109981,0.371734,-0.086809,0.260217,...,-1.970588,-0.068563,-1.601476,0.582609,-0.154509,-0.217193,-1.027851,0.062932,-0.056198,-0.213372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-03-13,0.998368,-0.089893,-0.626747,0.145099,-0.635273,-0.295055,0.432025,0.371033,0.725208,-0.032132,...,-0.190698,1.355816,-0.285305,-0.094256,-0.116477,-0.102853,-0.021539,0.212477,0.071590,2.212313
2021-03-14,0.499699,-0.090105,0.241161,-0.056352,-0.067326,-0.299074,0.438807,0.374280,0.738321,-0.031751,...,-0.278217,0.241872,-0.219575,-0.234502,-0.145689,-0.087492,-0.635664,0.292573,0.003307,0.878628
2021-03-15,2.410208,-0.409926,-0.064675,0.508213,0.309079,-0.303089,0.445527,0.377506,0.751345,-0.031371,...,-0.021301,1.787259,-0.318164,0.419687,0.242106,0.438984,0.181021,2.043399,0.127292,0.819891
2021-03-16,1.042191,-0.222048,-0.064675,-0.740139,-0.174283,-0.307097,0.452187,0.380711,0.764280,-0.030992,...,-0.028163,1.340599,0.364056,-0.214809,0.555757,0.153641,0.338363,1.168402,0.099935,-0.155078
2021-03-17,-0.148854,0.011090,-0.064675,-0.063798,-0.067326,-0.682843,-0.356384,-0.271947,-0.726605,-0.115039,...,-0.131220,-0.090466,-0.059012,-0.030641,-0.099432,-0.087811,-0.113303,-0.063296,-0.014755,-0.104477